/* Nieoficjalny atlas poglądowy. Geometria jest autorskim uproszczeniem mapy powieści. */
const SOURCE={anime:'https://mushokutensei.jp/story/',map:'https://ranobeki.com/en/series/mushoku-tensei/chapter-37',reference:'https://www.baka-tsuki.org/project/index.php?title=File%3AWorld_Map_3.png',s3:'https://mushokutensei.jp/news/250706_1/'};
const COLORS={1:'#d9b777',2:'#79b2ca',3:'#d58561'};
const continents=[
 {id:'central',name:'Kontynent Centralny',short:'CENTRALNY',tone:'#778e78',edge:'#3f625f',top:'#a5ad84',pts:[[100,245],[112,194],[152,157],[214,143],[254,112],[317,125],[361,155],[407,148],[448,176],[507,160],[570,192],[608,230],[595,278],[612,310],[583,351],[609,390],[585,453],[541,501],[489,523],[448,485],[396,512],[339,478],[288,478],[249,453],[207,464],[162,425],[142,381],[108,346],[130,302]],desc:'Największy obszar świata. Zachód należy do Asury, północ jest chłodna i politycznie rozdrobniona, południe ma własne królestwa.'},
 {id:'heaven',name:'Kontynent Niebiański',short:'NIEBIAŃSKI',tone:'#9ba69c',edge:'#647b83',top:'#d5c6a8',pts:[[455,90],[477,64],[535,47],[581,61],[624,85],[638,115],[609,142],[556,149],[514,134],[477,137],[449,113]],desc:'Wysoko położony płaskowyż ludu niebiańskiego. W opowieści ma znaczenie głównie dla geografii świata.'},
 {id:'demon',name:'Kontynent Demonów',short:'DEMONÓW',tone:'#9c7059',edge:'#6f4842',top:'#ca9066',pts:[[668,207],[698,174],[755,159],[803,182],[858,169],[911,196],[931,236],[923,273],[942,318],[918,357],[884,380],[868,415],[827,423],[784,400],[752,415],[713,384],[684,347],[693,307],[664,269]],desc:'Surowa kraina wielu ludów demonicznych i groźnych potworów. Tu trafiają Rudeus i Eris po katastrofie teleportacyjnej.'},
 {id:'millis',name:'Kontynent Millis',short:'MILLIS',tone:'#648e72',edge:'#315f62',top:'#93ba82',pts:[[657,473],[692,443],[734,443],[771,461],[808,463],[835,493],[830,527],[807,560],[786,594],[744,618],[704,598],[677,566],[665,529],[644,502]],desc:'Północ pokrywa Wielki Las, południe wiąże się z religią Millis. Przez kontynent biegnie Trakt Świętego Miecza.'},
 {id:'begaritt',name:'Kontynent Begaritt',short:'BEGARITT',tone:'#a98857',edge:'#775c45',top:'#d3ad6b',pts:[[294,546],[329,517],[374,508],[407,526],[446,502],[487,513],[529,541],[550,578],[525,613],[483,635],[425,627],[383,646],[340,620],[314,585]],desc:'Kraina pustyń, anomalii magicznych i labiryntów. Tu rozgrywa się wyprawa ratunkowa drugiego sezonu.'}
];
const places=[
 {id:'fittoa',name:'Region Fittoa',sub:'Bohater zaczyna tu nowe życie',continent:'central',x:260,y:350,seasons:[1],symbol:'⌂',ep:'S1 · odc. 1–8',lead:'Dom dzieciństwa Rudeusa i punkt, z którego rozchodzi się cała mapa podróży.',story:'W wiosce Buena dorasta pod opieką Paula i Zenith, uczy się magii od Roxy, a później trafia do rodziny Boreasów w Roa. Katastrofa teleportacyjna rozrzuca mieszkańców regionu po świecie.',links:['Buena','Roa','Katastrofa teleportacyjna']},
 {id:'buena',name:'Wioska Buena',sub:'Rodzina Greyratów',continent:'central',x:244,y:334,seasons:[1],symbol:'⌂',ep:'S1 · odc. 1–5',lead:'Pierwszy dom Rudeusa w świecie ludzi.',story:'Tu Rudeus przełamuje lęk przed wyjściem z domu, poznaje Sylphie i odkrywa swój talent do magii bez inkantacji.',links:['Rudeus','Sylphie','Roxy']},
 {id:'roa',name:'Roa',sub:'Dom Boreasów i Eris',continent:'central',x:283,y:366,seasons:[1],symbol:'♜',ep:'S1 · odc. 5–8',lead:'Miasto, w którym Rudeus zostaje nauczycielem Eris Boreas Greyrat.',story:'Relacja z Eris i Ghislaine prowadzi go poza spokojne życie w Buena. Katastrofa teleportacyjna przerywa tę część jego dzieciństwa.',links:['Eris','Ghislaine','Fittoa']},
 {id:'asura',name:'Królestwo Asura',sub:'Zachód Kontynentu Centralnego',continent:'central',x:210,y:315,seasons:[1,2],symbol:'♛',ep:'S1–S2 · tło polityczne',lead:'Najbogatsze królestwo świata i ojczyzna rodziny Boreasów.',story:'Asura zajmuje zachodnią część Kontynentu Centralnego. Los księżniczki Ariel łączy się z Sylphie, a polityka królestwa nabiera znaczenia w drugim sezonie.',links:['Ariel','Sylphie','Roa']},
 {id:'red-dragon',name:'Góry Czerwonego Smoka',sub:'Bariera dzieląca kontynent',continent:'central',x:346,y:359,seasons:[1,2,3],symbol:'△',ep:'Geografia',lead:'Pasmo górskie oddzielające zachód, północ i południe kontynentu.',story:'Przejścia między krainami są ograniczone; dlatego podróże wokół kontynentu trwają długo, a trasa Rudeusa po teleportacji prowadzi przez inne lądy.',links:['Kontynent Centralny','Asura']},
 {id:'sword-sanctum',name:'Święta Kraina Miecza',sub:'Szkolenie Eris',continent:'central',x:197,y:166,seasons:[1,3],symbol:'⚔',ep:'S3 · odc. 1–2',lead:'Północny ośrodek szkoły Boga Miecza.',story:'Eris, wspierana przez Ghislaine, trenuje tu pod okiem Gala Fariona. Początek trzeciego sezonu pokazuje jej drogę do siły potrzebnej, by stanąć u boku Rudeusa.',links:['Eris','Ghislaine','Nina']},
 {id:'northlands',name:'Północne krainy',sub:'Wędrówka „Quagmire”',continent:'central',x:379,y:236,seasons:[2],symbol:'❄',ep:'S2 · odc. 1–4',lead:'Chłodne, rozbite politycznie ziemie, gdzie Rudeus szuka Zenith.',story:'Po rozstaniu z Eris Rudeus dołącza do drużyny Counter Arrow, podejmuje zlecenia i zyskuje przydomek Quagmire.',links:['Counter Arrow','Sara','Zenith']},
 {id:'sharia',name:'Sharia',sub:'Uniwersytet Magii Ranoa',continent:'central',x:389,y:200,seasons:[2,3],symbol:'✦',ep:'S2–S3 · główny węzeł',lead:'Dom Rudeusa w okresie studiów i życia rodzinnego.',story:'Na uniwersytecie spotyka Fittsa, Nanahoshi, Cliffa i Zanobę. W drugim sezonie zakłada rodzinę z Sylphie; w trzecim Sharia pozostaje centrum wydarzeń po lekturze dziennika i podjęciu decyzji o ochronie rodziny.',links:['Sylphie','Roxy','Nanahoshi','Zanoba']},
 {id:'red-wyrm-jaw',name:'Szczęki Czerwonego Smoka',sub:'Przejścia przez pasmo',continent:'central',x:390,y:405,seasons:[1,2],symbol:'◇',ep:'Geografia',lead:'Nieliczne przejścia przez góry Kontynentu Centralnego.',story:'W świecie, gdzie górskie pasmo ogranicza ruch, szlaki handlowe i porty są dla podróżnych równie ważne jak prosta odległość na mapie.',links:['Góry Czerwonego Smoka']},
 {id:'shirone',name:'Królestwo Shirone',sub:'Aisha, Lilia i Zanoba',continent:'central',x:528,y:416,seasons:[1,2],symbol:'♜',ep:'S1 · odc. 19–20',lead:'Południowe królestwo, w którym Rudeus ratuje Aishę i Lilię.',story:'Spotkanie z księciem Zanobą staje się ważne także później: w Sharii łączy ich wspólne zainteresowanie figurkami i badaniami.',links:['Aisha','Lilia','Zanoba']},
 {id:'east-port',name:'Wschodni Port',sub:'Przeprawa na kontynent',continent:'central',x:574,y:447,seasons:[1],symbol:'⚓',ep:'S1 · powrót',lead:'Port po wschodniej stronie Kontynentu Centralnego.',story:'Po podróży przez Millis drużyna Dead End dopływa tu i kontynuuje drogę przez południowe królestwa.',links:['Dead End','Millis']},
 {id:'dragon-king',name:'Królestwo Króla Smoków',sub:'Południe Kontynentu Centralnego',continent:'central',x:489,y:476,seasons:[1,2],symbol:'♛',ep:'S1–S2 · szlaki południa',lead:'Wielkie królestwo południowej części kontynentu.',story:'Region tworzy pomost między wschodnimi portami a królestwami południa. W mapie pełni rolę punktu orientacyjnego, nie pojedynczego miasta.',links:['Shirone','Wschodni Port']},
 {id:'rikaris',name:'Rikaris',sub:'Miasto wewnątrz krateru',continent:'demon',x:794,y:225,seasons:[1,3],symbol:'◈',ep:'S1 · odc. 10–11 / S3 · odc. 10',lead:'Miasto zbudowane w wielkim kraterze; w jego środku stoją ruiny zamku Kishirisu.',story:'Dead End podejmuje tu pierwsze zlecenia. W późniejszej wyprawie drużyna Rudeusa trafia do starego zamku Kishirisu i spotyka Atofe. Obrzeże krateru, przejścia i ruina są głównymi punktami orientacyjnymi; układ pojedynczych ulic w modelu 3D jest rekonstrukcją.',links:['Dead End','Ruijerd','Kishirika','Atofe'],source:'https://ncode.syosetu.com/n9669bk/72/'},
 {id:'demon-north',name:'Północ Demonów',sub:'Miejsce po teleportacji',continent:'demon',x:827,y:187,seasons:[1],symbol:'✶',ep:'S1 · odc. 9',lead:'Odległy punkt, w którym Rudeus i Eris budzą się po katastrofie.',story:'Spotykają Ruijerda Superdię i rozpoczynają długą drogę do Fittoa. Punkt ma charakter orientacyjny, bo dokładne współrzędne nie są ustalone.',links:['Rudeus','Eris','Ruijerd']},
 {id:'migurd-village',name:'Wioska Migurdów',sub:'Rodzinne strony Roxy',continent:'demon',x:765,y:212,seasons:[1],symbol:'⌂',ep:'S1 · odc. 9–10',lead:'Niewielka osada rodzinnego ludu Roxy niedaleko miejsca lądowania Rudeusa i Eris.',story:'Kręta droga przez skały zajmuje około trzech godzin, choć miejsce lądowania leży mniej niż kilometr od osady w linii prostej. Rikaris jest jeszcze około trzy dni marszu dalej. Autor opisuje kilkanaście półziemianek z dachami z pancerzy Wielkich Żółwi; największa skorupa ma około 20 metrów. Są też skromne pole, płot i wspólne palenisko. Dokładnego punktu wioski na mapie nie podano.',links:['Roxy Migurdia','Rudeus','Eris','Ruijerd','Wielki Żółw'],source:'https://ncode.syosetu.com/n9669bk/26/'},
 {id:'petrified-forest',name:'Las Petryfikacji',sub:'Na południe od Rikaris',continent:'demon',x:805,y:263,seasons:[1],symbol:'♠',ep:'S1 · podróż Dead End',lead:'Niebezpieczny skrót około dzień drogi na południe od Rikaris.',story:'Autor opisuje liczne ostre drzewa podobne do kości: las sprawia wrażenie skamieniałego. Drużyna Dead End ryzykuje drogę na skróty mimo obecności groźnych potworów. Granice i dokładna pozycja lasu na mapie są rekonstrukcją.',links:['Rikaris','Dead End','Wind Port'],source:'https://ncode.syosetu.com/n9669bk/34/'},
 {id:'demon-south-route',name:'Południowy szlak Dead End',sub:'Nienazwane miasta i posterunki',continent:'demon',x:792,y:322,seasons:[1],symbol:'↗',ep:'S1 · droga ku Wen Port',lead:'Długi korytarz podróży od Rikaris przez kolejne miasta ku morzu.',story:'Drużyna zatrzymuje się w kolejnych, często nienazwanych miastach na tydzień lub dwa, pracuje dla gildii i zbiera pieniądze na przeprawę. Autor podaje około piętnaście dni do pierwszego większego miasta i znacznie dłuższą drogę do portu. Pas trasy jest orientacyjny; atlas nie nadaje tym przystankom wymyślonych nazw.',links:['Rikaris','Dead End','Wen Port'],source:'https://ncode.syosetu.com/n9669bk/36/'},
 {id:'wind-port',name:'Wen Port',sub:'Wind Port w niektórych przekładach',continent:'demon',x:790,y:392,seasons:[1],symbol:'⚓',ep:'S1 · odc. 12–13',lead:'Południowy port, z którego prowadzi przeprawa na Millis.',story:'Kontrola szlaków morskich komplikuje przeprawę Ruijerda. Roxy i drużyna Rudeusa mijają się tu w drodze. Oficjalny zapis japoński odpowiada nazwie Wen Port.',links:['Millis','Roxy','Ruijerd'],source:'https://ncode.syosetu.com/n9669bk/38/'},
 {id:'zant-port',name:'Zant Port',sub:'Przystań na Millis',continent:'millis',x:790,y:477,seasons:[1],symbol:'⚓',ep:'S1 · odc. 13–14',lead:'Port na wschodzie kontynentu Millis.',story:'Dead End dociera tu z Kontynentu Demonów. Dalsza trasa prowadzi przez Wielki Las i do Millishion.',links:['Wind Port','Wielki Las']},
 {id:'great-forest',name:'Wielki Las',sub:'Wioska Doldia',continent:'millis',x:754,y:497,seasons:[1],symbol:'♣',ep:'S1 · odc. 15',lead:'Dom ludów zwierzoludzi i jeden z ważnych etapów podróży Dead End.',story:'Ulewa zatrzymuje drużynę w lesie. Rudeus poznaje społeczność Doldia i jej związki z późniejszymi studentkami Ranoa.',links:['Doldia','Ruijerd']},
 {id:'millishion',name:'Millishion',sub:'Jezioro Gran i Biały Pałac',continent:'millis',x:741,y:560,seasons:[1],symbol:'✧',ep:'S1 · odc. 16–17',lead:'Stolica Świętego Kraju Millis. Na jeziorze Gran stoi Biały Pałac; rzeka Nikolaus przepływa przez miasto.',story:'Zachodnia dzielnica skupia złotą katedrę, południowa srebrzystą Gildię Poszukiwaczy Przygód. Północ to dzielnica mieszkalna, wschód handlowa; siedem wież reguluje barierę i poziom wody. Tutaj Rudeus ponownie spotyka Paula po katastrofie teleportacyjnej. Układ ulic i bryły budynków w modelu 3D są rekonstrukcją.',links:['Paul','Zenith','Jezioro Gran','Biały Pałac']},
 {id:'west-port',name:'Zachodni Port',sub:'Przeprawa ku Asurze',continent:'millis',x:681,y:570,seasons:[1],symbol:'⚓',ep:'S1 · podróż Dead End',lead:'Port po zachodniej stronie Millis.',story:'Na mapie szlaku prowadzi ku Wschodniemu Portowi Kontynentu Centralnego. Nazwy portów bywają różnie transkrybowane w przekładach.',links:['Wschodni Port']},
 {id:'holy-sword-road',name:'Trakt Świętego Miecza',sub:'Oś transportowa Millis',continent:'millis',x:735,y:526,seasons:[1],symbol:'↗',ep:'Geografia',lead:'Długi, prosty trakt łączący ważne części kontynentu.',story:'Opis powieści wiąże drogę z legendą o świętym Millis. Zaznaczona pozycja wskazuje trasę, nie jedno miasto.',links:['Wielki Las','Millishion']},
 {id:'begaritt-desert',name:'Pustynia Begaritt',sub:'Wyprawa ratunkowa',continent:'begaritt',x:431,y:554,seasons:[2],symbol:'☼',ep:'S2 · odc. 19',lead:'Niebezpieczny ląd, który Rudeus przemierza, by pomóc Paulowi.',story:'Drużyna pokonuje pustynny krajobraz pełen potworów i anomalii. Wyprawa pokazuje skalę świata poza codziennym życiem w Sharii.',links:['Paul','Rapan']},
 {id:'rapan',name:'Rapan',sub:'Miasto labiryntów',continent:'begaritt',x:461,y:569,seasons:[2],symbol:'⌘',ep:'S2 · odc. 20–23',lead:'Baza drużyny ratunkowej poszukującej Zenith.',story:'W pobliskim Labiryncie Teleportacyjnym Rudeus odnajduje Roxy. Wyprawa kończy się ocaleniem Zenith, śmiercią Paula i trwałą zmianą w rodzinie.',links:['Zenith','Paul','Roxy']},
 {id:'labyrinth',name:'Labirynt Teleportacyjny',sub:'Zagadka Zenith',continent:'begaritt',x:479,y:594,seasons:[2],symbol:'◉',ep:'S2 · odc. 20–23',lead:'Wielopoziomowy labirynt pod Rapan.',story:'Magiczne kręgi łączą poziomy. Starcie z potężną hydrą pozwala uratować Zenith, ale Paul ginie, osłaniając syna.',links:['Rapan','Zenith','Paul']},
 {id:'chaos-breaker',name:'Chaos Breaker',sub:'Latająca forteca Perugiusa',continent:'heaven',x:550,y:106,seasons:[3],symbol:'✦',ep:'S3 · odc. 8–9',lead:'Latająca forteca; jej znak na mapie jest umowny.',story:'Rudeus i Nanahoshi spotykają Perugiusa, szukając wiedzy o stanie Zenith. Później choroba Nanahoshi uruchamia wyprawę po lekarstwo.',links:['Perugius','Nanahoshi','Zenith']},
 {id:'heaven',name:'Płaskowyż Niebiański',sub:'Kontynent ludu niebiańskiego',continent:'heaven',x:494,y:97,seasons:[1,2,3],symbol:'△',ep:'Geografia',lead:'Wysoko położony piąty kontynent.',story:'Według opisu mapy w powieści płaski obszar leży około 3000 metrów nad otoczeniem. Nie jest osią głównej wędrówki anime do S3E14.',links:['Kontynent Niebiański']}
];
const routes={
 1:[['buena','roa'],['roa','demon-north'],['demon-north','migurd-village'],['migurd-village','rikaris'],['rikaris','petrified-forest'],['petrified-forest','demon-south-route'],['demon-south-route','wind-port'],['wind-port','zant-port'],['zant-port','great-forest'],['great-forest','millishion'],['millishion','west-port'],['west-port','east-port'],['east-port','shirone'],['shirone','fittoa']],
 2:[['fittoa','northlands'],['northlands','sharia'],['sharia','begaritt-desert'],['begaritt-desert','rapan'],['rapan','labyrinth'],['labyrinth','sharia']],
 3:[['sword-sanctum','sharia'],['sharia','chaos-breaker'],['chaos-breaker','rikaris'],['rikaris','sharia']]
};
const events=[
 {s:1,ep:'01–05',title:'Drugie życie',text:'Buena, nauka magii u Roxy, przyjaźń z Sylphie i pierwsze wyjście poza rodzinny dom.',place:'buena'},
 {s:1,ep:'06–08',title:'Roa i katastrofa',text:'Rudeus uczy Eris. Teleportacja rozrzuca mieszkańców Fittoa po świecie.',place:'roa'},
 {s:1,ep:'09–10',title:'Wioska Migurdów',text:'Na pustkowiach Rudeus i Eris spotykają Ruijerda oraz rodzinny lud Roxy. Skorupy Wielkich Żółwi tworzą dachy osady.',place:'migurd-village'},
 {s:1,ep:'10–11',title:'Rikaris i Dead End',text:'Droga prowadzi do miasta w kraterze, gdzie drużyna podejmuje pierwsze zlecenia.',place:'rikaris'},
 {s:1,ep:'11–12',title:'Las i południowy szlak',text:'Za Rikaris leży Las Petryfikacji, a potem długa droga przez nienazwane miasta Kontynentu Demonów.',place:'petrified-forest'},
 {s:1,ep:'12–13',title:'Ku Wen Port',text:'Po niebezpiecznym szlaku przez Kontynent Demonów drużyna dociera do portu i przeprawy na Millis.',place:'wind-port'},
 {s:1,ep:'13–18',title:'Millis i Paul',text:'Przeprawa morska, Wielki Las, Millishion oraz trudne spotkanie ojca z synem.',place:'millishion'},
 {s:1,ep:'19–23',title:'Droga do domu',text:'Shirone, powrót w okolice Fittoa, spotkanie z Orstedem i rozstanie z Eris.',place:'shirone'},
 {s:2,ep:'00–04',title:'Północne krainy',text:'Sylphie jako Fitz; Rudeus wędruje z Counter Arrow i szuka Zenith.',place:'northlands'},
 {s:2,ep:'05–12',title:'Uniwersytet Ranoa',text:'Studia w Sharii, Nanahoshi, Zanoba, Cliff oraz ponowne spotkanie z Sylphie.',place:'sharia'},
 {s:2,ep:'13–18',title:'Rodzina i wezwanie',text:'Rudeus buduje dom, wspiera siostry i podejmuje decyzję o wyprawie po Zenith.',place:'sharia'},
 {s:2,ep:'19–23',title:'Begaritt i labirynt',text:'Rapan, odnalezienie Roxy, ratunek Zenith i śmierć Paula.',place:'rapan'},
 {s:2,ep:'24',title:'Dziedzictwo',text:'Powrót do Sharii i próba życia z konsekwencjami wyprawy.',place:'sharia'},
 {s:3,ep:'01',title:'Eris w Krainie Miecza',text:'Eris przybywa z Ghislaine do szkoły Gala Fariona i deklaruje, że chce pokonać Orsteda.',place:'sword-sanctum'},
 {s:3,ep:'02',title:'Rywalki i trzy style',text:'Trening Eris spotyka się z ambicją Niny oraz wizytą Reidy i Isolte.',place:'sword-sanctum'},
 {s:3,ep:'03',title:'Powrót do codzienności',text:'W Sharii Rudeus wraca na uczelnię; Roxy dołącza do rodziny i zaczyna uczyć.',place:'sharia'},
 {s:3,ep:'04',title:'Nowa ręka, nowa magia',text:'Zanoba i Cliff pomagają przy protezie, a Rudeus prosi Roxy o naukę magii wody.',place:'sharia'},
 {s:3,ep:'05',title:'Świętowanie',text:'Ślub Cliffa i Elinalise oraz rodzinne święto Norn i Aishy przypominają o domu.',place:'sharia'},
 {s:3,ep:'06',title:'Spotkanie z Sarą',text:'Rudeus towarzyszy Roxy przy ochronie księżniczki Ranoa i ponownie spotyka Sarę.',place:'sharia'},
 {s:3,ep:'07',title:'Czwarty etap',text:'Ludzie z uniwersytetu wybierają dalsze ścieżki, a Nanahoshi proponuje nowy krok w badaniach.',place:'sharia'},
 {s:3,ep:'08',title:'Chaos Breaker',text:'Rudeus szuka wiedzy o Zenith u Perugiusa na pokładzie latającej fortecy.',place:'chaos-breaker'},
 {s:3,ep:'09',title:'Choroba Nanahoshi',text:'Nagły kryzys zdrowia Nanahoshi zamienia wizytę w fortecy w wyścig po lekarstwo.',place:'chaos-breaker'},
 {s:3,ep:'10',title:'Kishirika i Atofe',text:'Wyprawa prowadzi do Rikaris i starego zamku Kishirisu w centrum krateru, gdzie drużyna spotyka Atofe.',place:'rikaris'},
 {s:3,ep:'11',title:'Punkt zwrotny 4',text:'Rudeus wraca z lekarstwem; nocą rada Hitogamiego zostaje przerwana przez tajemniczego gościa.',place:'sharia'},
 {s:3,ep:'12',title:'Koniec i początek',text:'Przybysz twierdzi, że jest Rudeusem z przyszłości, i ostrzega przed tragicznym ciągiem zdarzeń.',place:'sharia'},
 {s:3,ep:'13',title:'Dziennik',text:'Rudeus czyta zapis możliwej przyszłości i poznaje cenę błędnych decyzji.',place:'sharia'},
 {s:3,ep:'14',title:'Decyzja',text:'Po lekturze dziennika Rudeus zaczyna działać, aby ochronić rodzinę i uniknąć tragicznej przyszłości.',place:'sharia'}
];
const lore=[
 {num:'01',title:'Pięć kontynentów',text:'Świat Ludzi obejmuje Kontynent Centralny, Demonów, Millis, Begaritt i Niebiański. Morze między nimi sprawia, że geograficznie bliskie miejsca mogą być trudne do osiągnięcia.',source:SOURCE.map},
 {num:'02',title:'Szlaki morskie',text:'Podróż z Kontynentu Demonów do Centralnego wiedzie przez wyznaczone porty i Millis. To wyjaśnia ogromny łuk drogi Dead End w pierwszym sezonie.',source:SOURCE.reference},
 {num:'03',title:'Góry Czerwonego Smoka',text:'Pasmo dzieli Kontynent Centralny na trzy regiony: bogaty zachód Asury, chłodną północ i południe wielu królestw.',source:SOURCE.map},
 {num:'04',title:'Magia i teleportacja',text:'Katastrofa Fittoa jest punktem zwrotnym pierwszego sezonu. Później magiczne kręgi umożliwiają podróż do Begaritt i ruch w labiryncie.',source:SOURCE.anime},
 {num:'05',title:'Rasy i języki',text:'Na Kontynencie Demonów mieszkają liczne ludy demoniczne, na Millis ludzie i zwierzoludzie, a na wysoko położonym kontynencie lud niebiański. Świat jest wielokulturowy.',source:SOURCE.map},
 {num:'06',title:'Sześć światów',text:'Mitologia serii wspomina sześć światów. Mapa pokazuje główny obszar akcji — Świat Ludzi — jako płaszczyznę z reliefem, zgodnie z konwencją map powieści.',source:SOURCE.map},
 {num:'07',title:'Trzy szkoły miecza',text:'Styl Boga Miecza stawia na ofensywę; Styl Boga Wody na obronę i kontrę; Styl Boga Północy ceni elastyczność. Trening Eris eksponuje je na początku S3.',source:SOURCE.anime},
 {num:'08',title:'Labirynty Begaritt',text:'Kontynent ma wiele lochów i obszarów o nietypowej magii. Labirynt pod Rapan jest kluczowy dla końca drugiego sezonu.',source:SOURCE.map},
 {num:'09',title:'Chronologia anime',text:'Sezon 1 obejmuje podróż do domu po katastrofie; sezon 2 prowadzi od północy przez Sharię do Begaritt; sezon 3 do odcinka 14 koncentruje się na Eris, rodzinie, Nanahoshi oraz decyzjach po ostrzeżeniu z przyszłości.',source:SOURCE.anime}
 ,{num:'10',title:'Osada Migurdów',text:'Na północnych pustkowiach rodzina Roxy mieszka w skromnej osadzie. Autor opisuje półziemianki z dachami z pancerzy Wielkich Żółwi, wspólne palenisko i niewielkie pole.',source:'https://ncode.syosetu.com/n9669bk/26/'}
 ,{num:'11',title:'Krater Rikaris i Las Petryfikacji',text:'Rikaris wzniesiono w ogromnym kraterze. Dzień drogi na południe leży niebezpieczny las, którego ostre, kościste drzewa wyglądają na skamieniałe.',source:'https://ncode.syosetu.com/n9669bk/34/'}
];
const people=[
 {name:'Rudeus Greyrat',role:'Oś podróży · S1–S3',text:'Mag bez inkantacji. Od Buena przez Kontynent Demonów i Millis trafia do Sharii, później do Begaritt i z powrotem.'},
 {name:'Eris Boreas Greyrat',role:'Wojowniczka · S1, S3',text:'Towarzyszka drogi Dead End. W S3 trenuje w Świętej Krainie Miecza.'},
 {name:'Sylphiette / Fitz',role:'Magini · S1–S3',text:'Przyjaciółka Rudeusa z dzieciństwa, związana z Ariel i Uniwersytetem Magii Ranoa.'},
 {name:'Roxy Migurdia',role:'Nauczycielka · S1–S3',text:'Pierwsza mistrzyni Rudeusa; jej droga krzyżuje się z jego wyprawą do Rapan.'},
 {name:'Ruijerd Superdia',role:'Opiekun Dead End · S1',text:'Wojownik, który przeprowadza Rudeusa i Eris przez Kontynent Demonów.'},
 {name:'Paul Greyrat',role:'Ojciec · S1–S2',text:'Po katastrofie szuka rodziny; prowadzi wyprawę ratunkową po Zenith.'},
 {name:'Zenith Greyrat',role:'Cel poszukiwań · S1–S3',text:'Zaginiona po katastrofie w Fittoa; odnaleziona w Labiryncie Teleportacyjnym.'},
 {name:'Nanahoshi Shizuka',role:'Badaczka · S2–S3',text:'Bada przyzwania i drogę do własnego świata. Jej choroba napędza wyprawę w S3.'},
 {name:'Orsted',role:'Bóg Smoków · S1–S3',text:'Potężna postać, której spotkanie na trasie Dead End kształtuje decyzje Eris.'},
 {name:'Perugius Dola',role:'Władca Chaos Breaker · S3',text:'Mieszkaniec latającej fortecy, do którego Rudeus trafia po wiedzę o Zenith.'},
 {name:'Kishirika Kishirisu',role:'Cesarzowa demonów · S1, S3',text:'Jej wiedza i oczy demonów stają się ważne dla poszukiwań Nanahoshi.'},
 {name:'Atoferatofe',role:'Nieśmiertelna władczyni · S3',text:'Rudeus spotyka ją na Kontynencie Demonów w trakcie wyprawy po lekarstwo.'}
];

export { SOURCE, COLORS, continents, places, routes, events, lore, people };
